### ISSUE TITLE
Missing Documentation

### ISSUE THREAD

**Issue by chickahoona** [mawalu/hetzner-gitlab-runner#1]
First nice work, I was looking for something like this, yet your Readme lacks a bit the actual instructions.

I assume that you need to have 1 host somewhere, preconfigured with your config.toml somewhere static. One has to register this one host as runner with gitlab-ci and this custom mawalu/hetzner-gitlab-runner image instead of the normal gitlab ci image.

And that runner, will use hetzner to spawn new VMs, which then will do the actual build and so on.

If you would like that other people use this image actually, then you have to provide some instructions about how to get your code running.

**Comment by mawalu** [comment]
Hi, 
you can follow the [official gitlab](https://docs.gitlab.com/runner/executors/docker_machine.html) instructions for setting everything up. This image just includes the additional docker machine driver so it can be used as a drop in replacement.

I agree that this should be made more clear and I will update the readme.
