### ISSUE TITLE
General Questions about autoscaling & downscaling

### ISSUE THREAD

**Issue by chickahoona** [mawalu/hetzner-gitlab-runner#3]
Hi martin,

First thanks for hetzner-gitlab-runner. I find it amazing!

Some questions:

1) I have everything now running, a hetzner machine is spawning and doing the task. Yet after the task its not automatically deleted. How is deletion controlled?
2) My pipeline has multiple jobs that can run in parallel, yet the expected autospawning only spawned 1 runner. I assume that I can set `concurrent = 1` to 10 or something like that to allow more to spawn? Or would those jobs end up on the same runner?

Best regards
Sascha

**Comment by mawalu** [comment]
Hi Sascha,

 * With the default configuration a runner should be deleted after the job is completed. This is handled by the [gitlab docker machine runner](https://docs.gitlab.com/runner/executors/docker_machine.html).
 * I have to admit I don't know how you can configure gitlab to start multiple autoscaling runners for one pipeline. Again this is something that should be described in the gitlab docs

I hope this is somewhat helpful :)

**Comment by chickahoona** [comment]
Thanks. It pointed me into the right direction. The most useful page is this one here https://docs.gitlab.com/runner/configuration/autoscale.html that explains how the whole autoscaling and so on works.

Thanks alot!
