### ISSUE TITLE
Which gitlab/gitlab-runner image to replace?

### ISSUE THREAD

**Issue by L-U-C-K-Y** [mawalu/hetzner-gitlab-runner#4]
Hi @mawalu 

Many thanks for this repo, it already helped me in setting up docker machine with Hetzner.

I have installed Docker Machine + GitLab Runner on the server, but I am confused with the following instructions:

> just use this image as a drop in replacement for gitlab/gitlab-runner.

Which image am I supposed to replace? I have followed the GitLab docs (maybe I missed something).

Will open a PR with updated instructions if that's fine for you afterwards.

Thanks!

**Comment by mawalu** [comment]
This image can be used as image for the GitLab runner itself. Did you install the runner directly on your server without using docker? In that case you do not need the image but can just install the docker-machine driver for hetzner on the server as well.

**Comment by L-U-C-K-Y** [comment]
Thanks @mawalu 

Makes sense! I also found this guide that helped me with the setup: https://fotoallerlei.com/blog/post/2020/autoscaling-gitlab-runners-on-hetzner-cloud/post

Thanks again for this repo 😄 👍🏽
